name: Node.js Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to project directory
        working-directory: ./   # ensure this points to the folder containing package.json

      - name: Install dependencies
        run: npm install
        working-directory: ./   # same here

      - name: Build Docker image
        run: docker build -t devops-app .
